### ISSUE TITLE
Live Editor Failed error

### ISSUE THREAD

**Issue by exctsteel** [xAranaktu/FC-25-Live-Editor#14]
![resim_2024-12-07_002105217](https://github.com/user-attachments/assets/ed4b8eac-c676-46fc-a68a-2f176f859a0c)
As a solution, all the methods I researched in the forums did not work. I tried going offline and turned off the antivirus. I am using the latest version editor. Can anyone find a way?

**Comment by exctsteel** [comment]
logs says to ''No game processes'' , ''
Birkaç denemeden sonra Live Editor kararlı oyun sürecini bulamadı.''.

**Comment by xAranaktu** [comment]
Join [discord server](https://discord.gg/yxAbpmNaFX) and create new ticket with your live editor log files attached.

**Comment by exctsteel** [comment]
I live in Turkey, Discord is banned, I can't use it :D and VPNs don't work on my computer. I guess I'll just have to wait
