### ISSUE TITLE
V25.2.3 MENU

### ISSUE THREAD

**Issue by imdhonss** [xAranaktu/FC-25-Live-Editor#16]
![1](https://github.com/user-attachments/assets/725f875b-43c1-4737-9694-5f082058dbcd)

why did the menu in my LE change when I updated to v25.2.2, then I updated again to v25.2.23 and it changed the names of the menus in it..? such as player role and other traits, is there a solution..?

**Comment by xAranaktu** [comment]
You have deleted `loc\eng_us\localize.json` and that's why your menu look like that. The fix is simple. Download LE again and don't delete any files.
