### ISSUE TITLE
..

### ISSUE THREAD

**Issue by Mezesinho** [xAranaktu/FC-25-Live-Editor#17]
Czy mógłbyś naprawdę nie dawać tematów zakończonych jako zakończone, gdy one nie są? W lgoach nic nie mam żadnych errorów poprostu wczytuje gre pasek sie laduje do konca i wywala gre czego tu nie mozna zrozumiec a ty mnie na jakies tickety przekierowujesz gdzie nic nie wiadomo o co chodzi. Z gory sorry za agresywny styl pisania ale sadze ze powinenes zatrudnic kogos do pomocy

**Comment by xAranaktu** [comment]
Nie, nie mógłbym. Dla mnie temat jest zakończony. Od zgłaszania problemów jest server discord.
