### ISSUE TITLE
Live Editor bug?

### ISSUE THREAD

**Issue by SDavid33** [xAranaktu/FC-25-Live-Editor#18]
Hi!

Can you help me with this? Why LE look like this?

![fc25 live editor bug](https://github.com/user-attachments/assets/2e2a326a-0559-43bd-addb-401ba99450c1)

**Comment by thymeau** [comment]
I have the same issue, found any fixes sofar?

**Comment by SDavid33** [comment]
> I have the same issue, found any fixes sofar?

I found out on Discord server that this is a bug for AMD VGA users, but sadly there's no fix for this, unless if you have a monitor with HDR option. Sadly, I don't have any. :D
