### ISSUE TITLE
Nothing work

### ISSUE THREAD

**Issue by Mezesinho** [xAranaktu/FC-25-Live-Editor#5]
I wanna play the game but it's crashed. What I should do?

08:56:25.962093	INFO	Injected
08:56:25.962647	INFO	FC 25 Live Editor - v25.1.3
08:56:25.963016	INFO	Proc <FC25.exe> 0x140000000-0x1662B1000
08:56:25.963353	INFO	Module <FCLiveEditor.DLL> 0x7FFFD7D30000-0x7FFFD8270000
08:56:25.963701	INFO	CMD: FC25.exe -dataPath FIFAModData -dataPath FIFAModData
08:56:25.964082	FATAL	Can't find: C:\Program Files (x86)\Steam\steamapps\common\EA SPORTS FC 25\FIFAModData
08:56:25.964860	INFO	Load Config From C:\Program Files (x86)\Steam\steamapps\common\EA SPORTS FC 25\le_config.json
08:56:25.965543	INFO	Config Load Done
08:56:25.966133	INFO	Load Language - EN
08:56:25.969736	INFO	Language Loaded
08:56:25.970508	INFO	Engine Setup
08:56:25.972383	INFO	----------------------------[Context]---------------------------
08:56:25.972901	INFO	Live Editor DLL Path:    C:\Users\Administrator\Downloads\FC 25 LE v25.1.3
08:56:25.973284	INFO	Game Path:               C:\Program Files (x86)\Steam\steamapps\common\EA SPORTS FC 25
08:56:25.973770	INFO	Game Version:            1.0.116.40849
08:56:25.974209	INFO	----------------------------------------------------------------
08:56:25.974589	INFO	Init LUA Scripts Manager
08:56:25.975291	INFO	[LE::LUA::ScriptsManager::LoadVars] Start
08:56:25.975685	INFO	[LUA API] Run Code
08:56:25.976143	INFO	[LUA API] Run Code Success
08:56:25.976555	INFO	[LE::LUA::ScriptsManager::LoadVars] Done
08:56:25.977297	INFO	[LUA API] Init LIVE EDITOR LUA API V1
08:56:25.984513	INFO	[LUA API] Init LIVE EDITOR LUA API V2
08:56:25.985008	INFO	[LUA API] Load LIVE EDITOR v25.1.3 LUA API V2
08:56:25.985677	INFO	Init LUA Scripts Manager Done
08:56:25.987553	INFO	Waiting for Press Any Key Screen
08:56:32.005098	INFO	Initializing
08:56:33.380736	ERROR	AOB not found 48 8B 10 4C 8D 45 40 41 B9 04 01 00 00 48 89
08:56:38.336545	INFO	Initializing End
08:58:20.521428	INFO	Injected
08:58:20.521923	INFO	FC 25 Live Editor - v25.1.3
08:58:20.522392	INFO	Proc <FC25.exe> 0x140000000-0x1662B1000
08:58:20.523051	INFO	Module <FCLiveEditor.DLL> 0x7FFFD8030000-0x7FFFD8570000
08:58:20.523567	INFO	CMD: FC25.exe -dataPath FIFAModData -dataPath FIFAModData
08:58:20.523935	FATAL	Can't find: C:\Program Files (x86)\Steam\steamapps\common\EA SPORTS FC 25\FIFAModData
08:58:20.524591	INFO	Load Config From C:\Program Files (x86)\Steam\steamapps\common\EA SPORTS FC 25\le_config.json
08:58:20.525363	INFO	Config Load Done
08:58:20.527509	INFO	Load Language - EN
08:58:20.530641	INFO	Language Loaded
08:58:20.531578	INFO	Engine Setup
08:58:20.533521	INFO	----------------------------[Context]---------------------------
08:58:20.533996	INFO	Live Editor DLL Path:    C:\Users\Administrator\Downloads\FC 25 LE v25.1.3
08:58:20.534351	INFO	Game Path:               C:\Program Files (x86)\Steam\steamapps\common\EA SPORTS FC 25
08:58:20.534677	INFO	Game Version:            1.0.116.40849
08:58:20.535008	INFO	----------------------------------------------------------------
08:58:20.535362	INFO	Init LUA Scripts Manager
08:58:20.536039	INFO	[LE::LUA::ScriptsManager::LoadVars] Start
08:58:20.536415	INFO	[LUA API] Run Code
08:58:20.536893	INFO	[LUA API] Run Code Success
08:58:20.537418	INFO	[LE::LUA::ScriptsManager::LoadVars] Done
08:58:20.538477	INFO	[LUA API] Init LIVE EDITOR LUA API V1
08:58:20.545027	INFO	[LUA API] Init LIVE EDITOR LUA API V2
08:58:20.545489	INFO	[LUA API] Load LIVE EDITOR v25.1.3 LUA API V2
08:58:20.546025	INFO	Init LUA Scripts Manager Done
08:58:20.548226	INFO	Waiting for Press Any Key Screen
08:58:26.244829	INFO	Initializing
08:58:27.598863	ERROR	AOB not found 48 8B 10 4C 8D 45 40 41 B9 04 01 00 00 48 89
08:58:28.193607	INFO	Initializing End
09:01:05.076985	INFO	Injected
09:01:05.077372	INFO	FC 25 Live Editor - v25.1.3
09:01:05.077704	INFO	Proc <FC25.exe> 0x140000000-0x1662B1000
09:01:05.078030	INFO	Module <FCLiveEditor.DLL> 0x7FFFD8360000-0x7FFFD88A0000
09:01:05.078365	INFO	CMD: FC25.exe -dataPath FIFAModData -dataPath FIFAModData
09:01:05.078782	FATAL	Can't find: C:\Program Files (x86)\Steam\steamapps\common\EA SPORTS FC 25\FIFAModData
09:01:05.079386	INFO	Load Config From C:\FC 25 Live Editor\le_config.json
09:01:05.080068	INFO	Config Load Done
09:01:05.082485	INFO	Load Language - EN
09:01:05.085860	INFO	Language Loaded
09:01:05.086754	INFO	Engine Setup
09:01:05.088519	INFO	----------------------------[Context]---------------------------
09:01:05.089114	INFO	Live Editor DLL Path:    C:\Users\Administrator\Downloads\FC 25 LE v25.1.3
09:01:05.089589	INFO	Game Path:               C:\Program Files (x86)\Steam\steamapps\common\EA SPORTS FC 25
09:01:05.089948	INFO	Game Version:            1.0.116.40849
09:01:05.090305	INFO	----------------------------------------------------------------
09:01:05.090654	INFO	Init LUA Scripts Manager
09:01:05.091317	INFO	[LE::LUA::ScriptsManager::LoadVars] Start
09:01:05.091676	INFO	[LUA API] Run Code
09:01:05.092051	INFO	[LUA API] Run Code Success
09:01:05.092456	INFO	[LE::LUA::ScriptsManager::LoadVars] Done
09:01:05.093150	INFO	[LUA API] Init LIVE EDITOR LUA API V1
09:01:05.099463	INFO	[LUA API] Init LIVE EDITOR LUA API V2
09:01:05.099923	INFO	[LUA API] Load LIVE EDITOR v25.1.3 LUA API V2
09:01:05.100621	INFO	Init LUA Scripts Manager Done
09:01:05.102477	INFO	Waiting for Press Any Key Screen
09:01:10.739681	INFO	Initializing
09:01:12.101447	ERROR	AOB not found 48 8B 10 4C 8D 45 40 41 B9 04 01 00 00 48 89
09:01:12.694515	INFO	Initializing End
09:03:17.427326	INFO	Injected
09:03:17.427710	INFO	FC 25 Live Editor - v25.1.3
09:03:17.428055	INFO	Proc <FC25.exe> 0x140000000-0x1662B1000
09:03:17.428390	INFO	Module <FCLiveEditor.DLL> 0x7FFFD8030000-0x7FFFD8570000
09:03:17.428723	INFO	CMD: FC25.exe -dataPath FIFAModData -dataPath FIFAModData
09:03:17.429086	FATAL	Can't find: C:\Program Files (x86)\Steam\steamapps\common\EA SPORTS FC 25\FIFAModData
09:03:17.429689	INFO	Load Config From C:\FC 25 Live Editor\le_config.json
09:03:17.430314	INFO	Config Load Done
09:03:17.432603	INFO	Load Language - EN
09:03:17.435817	INFO	Language Loaded
09:03:17.436597	INFO	Engine Setup
09:03:17.438392	INFO	----------------------------[Context]---------------------------
09:03:17.438760	INFO	Live Editor DLL Path:    C:\FC 25 LE v25.1.3
09:03:17.439130	INFO	Game Path:               C:\Program Files (x86)\Steam\steamapps\common\EA SPORTS FC 25
09:03:17.439461	INFO	Game Version:            1.0.116.40849
09:03:17.439794	INFO	----------------------------------------------------------------
09:03:17.440142	INFO	Init LUA Scripts Manager
09:03:17.440758	INFO	[LE::LUA::ScriptsManager::LoadVars] Start
09:03:17.441172	INFO	[LUA API] Run Code
09:03:17.441564	INFO	[LUA API] Run Code Success
09:03:17.442065	INFO	[LE::LUA::ScriptsManager::LoadVars] Done
09:03:17.442759	INFO	[LUA API] Init LIVE EDITOR LUA API V1
09:03:17.448978	INFO	[LUA API] Init LIVE EDITOR LUA API V2
09:03:17.449367	INFO	[LUA API] Load LIVE EDITOR v25.1.3 LUA API V2
09:03:17.449889	INFO	Init LUA Scripts Manager Done
09:03:17.451755	INFO	Waiting for Press Any Key Screen
09:03:23.088643	INFO	Initializing
09:03:24.445674	ERROR	AOB not found 48 8B 10 4C 8D 45 40 41 B9 04 01 00 00 48 89
09:03:25.033592	INFO	Initializing End
09:07:34.398222	INFO	Injected
09:07:34.398613	INFO	FC 25 Live Editor - v25.1.3
09:07:34.398951	INFO	Proc <FC25.exe> 0x140000000-0x1662B1000
09:07:34.399327	INFO	Module <FCLiveEditor.DLL> 0x7FFFD8030000-0x7FFFD8570000
09:07:34.399724	INFO	CMD: FC25.exe -dataPath FIFAModData
09:07:34.400117	FATAL	Can't find: C:\Program Files (x86)\Steam\steamapps\common\EA SPORTS FC 25\FIFAModData
09:07:34.400763	INFO	Load Config From C:\FC 25 Live Editor\le_config.json
09:07:34.401547	INFO	Config Load Done
09:07:34.403805	INFO	Load Language - EN
09:07:34.407571	INFO	Language Loaded
09:07:34.408544	INFO	Engine Setup
09:07:34.410426	INFO	----------------------------[Context]---------------------------
09:07:34.410974	INFO	Live Editor DLL Path:    C:\FC 25 LE v25.1.3
09:07:34.411327	INFO	Game Path:               C:\Program Files (x86)\Steam\steamapps\common\EA SPORTS FC 25
09:07:34.411656	INFO	Game Version:            1.0.116.40849
09:07:34.412002	INFO	----------------------------------------------------------------
09:07:34.412377	INFO	Init LUA Scripts Manager
09:07:34.412994	INFO	[LE::LUA::ScriptsManager::LoadVars] Start
09:07:34.413358	INFO	[LUA API] Run Code
09:07:34.413823	INFO	[LUA API] Run Code Success
09:07:34.414220	INFO	[LE::LUA::ScriptsManager::LoadVars] Done
09:07:34.414950	INFO	[LUA API] Init LIVE EDITOR LUA API V1
09:07:34.421120	INFO	[LUA API] Init LIVE EDITOR LUA API V2
09:07:34.421492	INFO	[LUA API] Load LIVE EDITOR v25.1.3 LUA API V2
09:07:34.421988	INFO	Init LUA Scripts Manager Done
09:07:34.423816	INFO	Waiting for Press Any Key Screen
09:07:40.183484	INFO	Initializing
09:07:41.566341	ERROR	AOB not found 48 8B 10 4C 8D 45 40 41 B9 04 01 00 00 48 89
09:07:42.165869	INFO	Initializing End
09:09:30.874730	INFO	Injected
09:09:30.875111	INFO	FC 25 Live Editor - v25.1.3
09:09:30.875444	INFO	Proc <FC25.exe> 0x140000000-0x1662B1000
09:09:30.875777	INFO	Module <FCLiveEditor.DLL> 0x7FFFD8330000-0x7FFFD8870000
09:09:30.876121	INFO	CMD: FC25.exe -dataPath FIFAModData
09:09:30.876495	FATAL	Can't find: C:\Program Files (x86)\Steam\steamapps\common\EA SPORTS FC 25\FIFAModData
09:09:30.877092	INFO	Load Config From C:\FC 25 Live Editor\le_config.json
09:09:30.877701	INFO	Config Load Done
09:09:30.879986	INFO	Load Language - EN
09:09:30.883355	INFO	Language Loaded
09:09:30.884203	INFO	Engine Setup
09:09:30.885990	INFO	----------------------------[Context]---------------------------
09:09:30.886388	INFO	Live Editor DLL Path:    C:\FC 25 LE v25.1.3
09:09:30.886872	INFO	Game Path:               C:\Program Files (x86)\Steam\steamapps\common\EA SPORTS FC 25
09:09:30.887266	INFO	Game Version:            1.0.116.40849
09:09:30.887644	INFO	----------------------------------------------------------------
09:09:30.887989	INFO	Init LUA Scripts Manager
09:09:30.888729	INFO	[LE::LUA::ScriptsManager::LoadVars] Start
09:09:30.889142	INFO	[LUA API] Run Code
09:09:30.889553	INFO	[LUA API] Run Code Success
09:09:30.889968	INFO	[LE::LUA::ScriptsManager::LoadVars] Done
09:09:30.890759	INFO	[LUA API] Init LIVE EDITOR LUA API V1
09:09:30.896763	INFO	[LUA API] Init LIVE EDITOR LUA API V2
09:09:30.897329	INFO	[LUA API] Load LIVE EDITOR v25.1.3 LUA API V2
09:09:30.897858	INFO	Init LUA Scripts Manager Done
09:09:30.899693	INFO	Waiting for Press Any Key Screen
09:09:36.821229	INFO	Initializing
09:09:38.187616	ERROR	AOB not found 48 8B 10 4C 8D 45 40 41 B9 04 01 00 00 48 89
09:09:38.784999	INFO	Initializing End

**Comment by xAranaktu** [comment]
Your antivirus is blocking Live Editor.

**Comment by Mezesinho** [comment]
still not working
